#+TITLE: Why another provisioning tool?

The space/problem seems already solved given how Ansible consolidated itself as the leader in it. However, as with any approach, there's always a set of trade-offs that might not appeal to certain people. Encoding your infrastucture became essential to everyone that want repetability in their systems, but there are different ways to do it, and this will be another one!

* What's the problem with Ansible?

- Ansible is great to lay out steps declaratively, but not everything is as simple as a simple task
- Conditionals, blocks, loops, variables, ... why create everything else in a data serialization language?
- You need to read pages and pages to know how to even start, and you need a book to be sufficiently proficient in it
- "Shelling out" could be simpler. It might be, but the documentation wall didn't guide me there yet. You need to write a plugin just to use reasonable control structures with python, but doing that isn't that straightforward
- The plugins system is amazing! But installing them and managing its paths isn't


* Why not Pyinfra?

- Compare the link task with a pyinfra alternative, and how the documentation is so much simpler!

Ansible:

#+BEING_SRC yaml
- name: Find directories
  find:
    paths: "{{ src }}"
    file_type: directory
    hidden: true
    recurse: true
    patterns: "*"
  register: directories

- name: Create directories
  file:
    path: "{{ dest }}/{{ item }}"
    state: directory
  loop: "{{ directories.files | flatten(levels=1) | map(attribute='path') | map('regex_replace', '^' + src + '/(.+)$', '\\1') }}"

- name: Find files
  find:
    paths: "{{ src }}"
    file_type: file
    hidden: true
    recurse: true
    patterns: "*"
  register: files

- name: Link files
  file:
    force: true
    state: link
    src: "{{ item }}"
    dest: "{{ dest }}/{{ file }}"
  loop: "{{ files.files | flatten(levels=1) | map(attribute='path') }}"
  vars:
    file: "{{ item | regex_replace('^' + src + '/(.+)$', '\\1') }}"
  loop_control:
    label: "{{ file }}"

- name: Find links
  find:
    paths: "{{ src }}"
    file_type: link
    hidden: true
    recurse: true
    patterns: "*"
  register: links

- name: Link links
  file:
    force: true
    state: link
    src: "{{ item }}"
    dest: "{{ dest }}/{{ file }}"
  loop: "{{ links.files | flatten(levels=1) | map(attribute='path') }}"
  vars:
    file: "{{ item | regex_replace('^' + src + '/(.+)$', '\\1') }}"
  loop_control:
    label: "{{ file }}"
#+END_SRC

Pyinfra:

#+BEING_SRC python
@operation()
def directories(source, target):
    yield from files.directory._inner(
        path=target,
        present=True,
    )

    for path in Path(source).rglob('*'):
        if path.is_dir():
            relative_to_source = str(path.relative_to(Path(source)))
            in_target = Path(target) / relative_to_source

            yield from files.directory._inner(
                path=str(in_target),
                present=True,
            )

@operation()
def links(source, target):
    yield from directories._inner(source, target)

    for path in Path(source).rglob('*'):
        if path.is_file():
            relative_to_source = str(path.relative_to(Path(source)))
            in_target = Path(target) / relative_to_source

            yield from files.link._inner(
                path=str(in_target),
                target=str(path),
                present=True,
                symbolic=True,
                force=True,
            )
#+END_SRC

- It's "plan and apply" approach sounds great, but it's really difficult to describe the state of highly stateful things. It's one thing to describe settings, it's a whole different thing to describe changes to a system. Declaring state like it does is like expecting your business rules to amount to a final result, that depends on previous steps, but you can't execute the dependencies to know how the plan will pan out.
    - How would one encode the moduli change from the SSH hardening guide into a fully declarative thing? In this case the file might be standard, but that isn't always true. Is it worth it to figure out a way to describe a possibly criptic final state when describing its state changes are simply easier?
- It does too much magic behind the scenes that when you need to control it, it's a whole different system. Though it uses a programming language by default, it's too CLI centered. It's similar to ansible in this regard where it could be more extensible

* Why Izumi?

- Use a programming language that has become popular in infrastructure projects, and don't bring any additional shenanigans. WYSIWYG; it's just a way to achieve reusable commands and queries over an abstracted connection
- Make it as simple as possible, with a streamlined architecture that anyone could understand after 1h reading through the project, and where it's easy to start and extend. Pyinfra did this beatifully on the documentation side, and we should follow
- Plugging in shouldn't be hard, the interfaces will be simple and extensible. It'd be nice to support custom logging, reacting to changes, trigerring handlers, ...
- CLI as an afterthought. It shouldn't be the main focus; the same code you'd run inside a Go project should be used if fired from the CLI itself. It could be a simple "go run" on the inside that executes a provisioning "playbook"
